server:
  port: 10110

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0 # Database index used by the connection factory.
    timeout: 0 # Connection timeout in milliseconds.
    pool:
      max-active: 8 # Max number of connections that can be allocated by the pool at a given time. Use a negative value for no limit.
      max-idle: 8 # Max number of "idle" connections in the pool. Use a negative value to indicate an unlimited number of idle connections.
      max-wait: -1 # Maximum amount of time (in milliseconds) a connection allocation should block before throwing an exception when the pool is exhausted. Use a negative value to block indefinitely.
      min-idle: 1 # Target for the minimum number of idle connections to maintain in the pool. This setting only has an effect if it is positive.

#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://172.17.110.213/db3?useUnicode:true&characterEncoding=utf-8&autoReconnect=true
    username: esb
    password: esb
  redis:
    host: 172.19.103.47
    port: 6379
    password: redis!@456

